
include:
  - ros-helix-proprietary/docker-compose.yml

services:
  nginx:
    image: nginx
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ros-helix-proprietary/helix_description/meshes:/usr/share/nginx/html/meshes
    network_mode: "host"
    restart: always

  studio:
    image: ghcr.io/eai-ag/studio:latest
    build:
      context: studio
      dockerfile: Dockerfile
    volumes:
      - ./config/studio/layout.json:/lichtblick/default-layout.json
    ports:
      - 8080:8080
    restart: always
